export const ActionTypes = {
    FETCH_CARS: 'FETCH_CARS',
    SET_CARS: 'SET_CARS',
    SELECTED_CAR: 'SELECTED_CAR',
    SET_SHOW: 'SET_SHOW',
    SET_BUTTON: 'SET_BUTTON',
    SET_RESULT: 'SET_RESULT',
};