export const ActionTypes = {
    FETCH_CARS: 'FETCH_CARS',
    FETCH_CARS1: 'FETCH_CARS1',
    SET_CARS: 'SET_CARS',
    SELECTED_CAR: 'SELECTED_CAR',
    SELECTED_CAR1: 'SELECTED_CAR1',
    SET_SHOW: 'SET_SHOW',
    SET_SEARCH_STATUS: 'SET_SEARCH_STATUS',
};